test-resources/conf.d/webserver.conf
test/puppetlabs/pcp/broker/service_test.clj
test/puppetlabs/pcp/testutils/client.clj

During development we were setting up our test brokers on port 8080 and 8090
(non-ssl and ssl).  Now the 'production' port will be, for a time, 8142.
Update the sample config to use 8142 and the tests to use 8143 (so we can run a
sample server and the tests concurrently)

(maint) change default port to 8142

---

CHANGELOG.md

Here we add a CHANGELOG.md and document the difference between 0.2.1
and 0.2.2.

Prepare for the 0.2.2 release

---

CONTRIBUTING.md
README.md

Here we add a CONTRIBUTING.md, a forward reference to our issue tracker to the
README.md, and make the CHANGELOG.md follow the same format as that established
by trapperkeeper-webserver-jetty9 in preparation of being an official
PuppetLabs open library.

(maint) prepare to be an open project

---

project.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
test/puppetlabs/pcp/broker/core_test.clj
test/puppetlabs/pcp/broker/service_test.clj

In the past the server URI was hardcoded to be pcp:///server, the URI
used by clients when addressing the server.
Here we update the broker-uri fn to return the correct server URI based
on the cn in it's ssl-certificate. The ssl-cert is determined by looking
up the server value in the :websocket route, or directly from the server
if there is only one configured.

(CTH-134) Message hops should include the server identity

---

resources/ext/config/conf.d/metrics.conf
resources/ext/config/conf.d/pcp-broker.conf
resources/ext/config/conf.d/web-routes.conf
resources/ext/config/conf.d/webserver.conf
test-resources/conf.d/metrics.conf
test-resources/conf.d/web-router.conf
test-resources/conf.d/web-routes.conf
test-resources/conf.d/webserver.conf

Here we add some reference configurations, based on the previous test-resources
configurations, but ready for consumption by an ezbake built service wrapper.
We have moved from using the default unnamed trapperkeeper webserver to
a named webserver called "pcp-broker", to allow easier integration with other
services that need their own uniquely configured webservers.
Symlinks from the common resources have been added to the test-resources
directory, to reduce duplication where possible.

PCP-37 Add reference configs to resources/ext for ezbake

---

doc/authorization.md
src/puppetlabs/pcp/broker/core.clj
test/puppetlabs/pcp/broker/core_test.clj
test/puppetlabs/pcp/broker/service_test.clj

The structure of the query-params to a ring request is {String String}.  Previously we were supplying {:keyword String}, which meant trapperkeeper-authorization was not able to correctly match on query-params.

Correct the structure of the fake ring request

---

doc/logging.md
project.clj
src/puppetlabs/pcp/broker/activemq.clj
src/puppetlabs/pcp/broker/capsule.clj
src/puppetlabs/pcp/broker/connection.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
test-resources/logback-dev.xml
test/puppetlabs/pcp/broker/connection_test.clj
test/puppetlabs/pcp/broker/core_test.clj

Here we restructure a little and introduce puppetlabs/structured-logging
throughout the code.
All log statements (outside of puppetlabs.puppetdb.mq) become
sl/maplog calls, with a :type field and data relevant to the message
being logged.  Consult doc/logging.md for explanations of the types
and the other logged data.
Connection type and its helpers are moved into its own
`puppetlabs.pcp.broker.connection` namespace.
`Capsule`s and `Connection`s gain a summarize helper to expose the
inspectable/loggable parts, using the pattern of `(foo/summarize :- FooLog [foo :- Foo])`,
so we can verify the structure of our structured logging.
Set the development logfile to log puppetlabs.pcp.broker at TRACE, which after
other changes is still fairly quiet.

PCP-115 Convert logging to structured-logging, and reword

---

doc/logging.md
src/puppetlabs/pcp/broker/core.clj
test/puppetlabs/pcp/broker/service_test.clj

Here we protect the broker from weirdness by just disconnecting any connection
that doesn't have a peer certificate, in the on-connect handler.

PCP-124 Close the connection when no peer certificate

---

src/puppetlabs/pcp/broker/core.clj
test/puppetlabs/pcp/broker/service_test.clj

Here we change the behaviour of inventory queries to only report on identites
that are currently connected to the broker.  This is a behavioural change, but
it's more in line with peoples expectations of this API.

PCP-132 inventory queries should only report on connected clients

---

src/puppetlabs/pcp/broker/core.clj
test/puppetlabs/pcp/broker/core_test.clj

Here we extract the computation of the retry delay to its own function, and
test that it now returns a value in the range 1..15 seconds.   15 seconds as an
upper bound has been chosen somewhat arbritarily based on the maximum reconnect
delay in pxp-agent being in the 30 seconds realm.

PCP-126 limit the range of retry delay

---

project.clj
test/puppetlabs/pcp/broker/service_test.clj

Here we try and minimize the impact of a slightly broken test.  We seem to have races between the test client having its internal state reflect that it was connected, and the server shutting it down because no client certificate was presented.

PCP-124 minimize racy test

---

src/puppetlabs/pcp/broker/core.clj

Here we add a missing argument to the call to capsule/summarize in the
process-expired-message function.

(maint) Fix capsule/summarize invocation

---

src/puppetlabs/pcp/broker/core.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

Here we add some very basic unit tests to important functions in the core broker namespace.  This bumps our basic coverage up by ~11% by form, ~18% by line and gives us some tests to develop further.
master:
```
Forms covered: 34.09 %
Lines covered: 44.35 %
```
with this PR:
```
Forms covered: 45.47 %
Lines covered: 62.15 %
```

PCP-147 improve broker unit test

---

doc/configuration.md
project.clj
resources/ext/config/conf.d/web-routes.conf
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/metrics.clj
src/puppetlabs/pcp/broker/service.clj
test-resources/bootstrap.cfg
test/integration/puppetlabs/pcp/broker/service_test.clj

With this set of changes we move from having a home-grown ring app called `metrics` mounted by convention at "/" to using trapperkeeper-status.  
As a convenience the test configuration mounts the trapperkeeper-status application at the more conventional "/status" path so statistics may now be queried with `curl -k  'https://localhost:8142/status/v1/services/broker-service?level=debug'`

PCP-193 move metrics to trapperkeeper-status

---

doc/configuration.md
resources/ext/config/conf.d/web-routes.conf
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
test/integration/puppetlabs/pcp/broker/service_test.clj

Here we rename the existing `websocket` route-id to `v1` to more clearly
associate the mounted handler with the version of the PCP protocol it
supports.
It is expected the v2 handler, when created, will have a default mountpoint of
`/pcp/v2` like so:
web-router-service: {
"puppetlabs.pcp.broker.service/broker-service": {
v1: "/pcp"
v2: "/pcp/v2"
}
}

PCP-199 Rename `websocket` route-id

---

resources/ext/config/conf.d/web-routes.conf

PCP-193 (merged as 28e5329) removed the metrics endpoint from the broker.  Here
we tidy up the web-routes configuration.

(maint) cleanup released web-routes.conf

---

resources/ext/config/conf.d/authorization.conf

As this rule comes from a package it should have a sort order in
the range 400-600 so that users can override with rules earlier and augment
with rules later.

(PCP-222) Correct the ordering of the default rule

---

doc/README.md
doc/logging.md

Here we add the logging level rationale from PCP-5 to the doc/logging.md where
it will be the most useful, and also call out which level each message will be
seen at.

(maint) explain more about the loglevels in use

---

src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/utils/puppetlabs/pcp/testutils/client.clj

The "in-reply-to" envelope property was initially added to the
inventory_response codepath in commit 92b66d1c.  Here we change the
behaviour of the broker to supply this property whenever we are
clearly responding to a message, allowing a client to correlate a
response with its original request.

PCP-195 Supply "in-reply-to" header when responding to a message

---

src/puppetlabs/pcp/broker/activemq.clj
src/puppetlabs/pcp/broker/capsule.clj
src/puppetlabs/pcp/broker/connection.clj
src/puppetlabs/pcp/broker/core.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

The previous implementation of Capsule and Connection are straight clojure maps
with validation using schemas.  Here we swap these maps for records, as this
provides a slighly tighter in-memory representation, and also introduces a more
explicit interface for these types.

PCP-194 Make Capsule and Connection types records

---

src/puppetlabs/pcp/broker/activemq.clj
src/puppetlabs/pcp/broker/borrowed/cheshire.clj
src/puppetlabs/pcp/broker/borrowed/mq.clj
src/puppetlabs/pcp/broker/core.clj

This commit renames the namespaces copied from PuppetDB so that they are
unique to this project. This avoids conflicts with PuppetDB that arise
from having two (now different!) namespaces with the same name.
Similarly, changed the name of the embedded broker from "localhost" to
"pcp" to allow for multiple ActiveMQ instances to be started in the same
process.
These changes are meant to enable pcp-broker to be embedded in the same
jar/process as PuppetDB. Eventually this code probably ought to be
migrated to shared libraries or a dedicated trapperkeeper service (for
ActiveMQ), but for now this avoids conflicts.

(maint) Remove naming conflicts with PuppetDB

---

doc/configuration.md
resources/ext/config/conf.d/web-routes.conf
src/puppetlabs/pcp/broker/capsule.clj
src/puppetlabs/pcp/broker/connection.clj
src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/connection_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/utils/puppetlabs/pcp/testutils.clj
test/utils/puppetlabs/pcp/testutils/client.clj

We dub the developing version of the protocol "vNext" for now, as
it is a developing set of changes to the already established PCP
v1.0, and give it the websockets route :vNext.
Due to the closeness of v1.0 and vNext (vNext currently just adds
the optional in-reply-to header to all reply types), the brokers
internal representation of messages is vNext, which we then transform
when sending/receiving message via a Codec which is a property of
the connection derived from the uri the connection was established
on.

PCP-250 Add multiple protocol version support

---

src/puppetlabs/pcp/broker/core.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

Here we make the trapperkeeper-status endpoint more useful by actually tracking
the broker-service state so we can return a usable value to the server status
api.
$ while true ; do  curl -sk https://127.0.0.1:8142/status/v1/services/broker-service | jq ".state" ; done
"starting"
"starting"
"starting"
"starting"
"running"
"running"

PCP-295 Track and return the service status

---

project.clj

Here we bump the trapperkeeper dependency up to 1.3.0 so in future
we can make use of the HUP handling added for TK-202.
In order to reduce some dependency clash, we no longer state our
dependencies on prismatic/schema, org.clojure/core.async, and
me.raynes/fs and instead resolve them transitively via
puppetlabs/trapperkeeper, and puppetlabs/kitchensink.

PCP-301 update trapperkeeper to 1.3.0 for HUP

---

doc/configuration.md
resources/ext/config/conf.d/web-routes.conf
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
test-resources/conf.d/web-routes.conf

Here we conditionally guard the mounting of the vNext protocol
handler behind it having a mountpoint present in the web-router
configuration.  This will allow existing users to leave the developing
protocol support disabled until it becomes important enough to make
the configuration of it via webroutes mandatory.
As vNext isn't finalised/public yet, remove it from the default
web-routes.conf that ezbake will publish, and add a more specific
test-resources/conf.d/web-routes.conf.

PCP-292 Only mount vNext when a web-route is supplied.

---

src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/utils/puppetlabs/pcp/testutils/client.clj

These set of commits adds the 3 missing checks of message expiry; during association, once associated before persisting the message to the deliver queue, and an consumption of the message from the delivery queue.

PCP-245 check message expiry consistently

---

README.md

The "Support" section is redundant as we have now the "Maintenance"
section that explains how to fill tickets; with this commit, we remove
"Support".

(maint) Remove Support section from README

---

project.clj

Bumping trapperkeeper-webserver-jetty9 to 1.5.7 as a recommended bugfix
is included; updating associated dependencies, including trapperkeeper
1.4.0. Note that, this time, we're not bumping clojure to 1.7.0.

(maint) Bump trapperkeeper-webserver-jetty9 to 1.5.7

---

src/puppetlabs/pcp/broker/core.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

Many Jetty threads can result in modifying the connections or uri map.
When many updates occur concurrently, we can see lots of failed atom
updates resulting in much slower processing.
Switch to using a ConcurrentHashMap. It appears to scale better, and is
at least as fast for smaller numbers of clients.

(PCP-448) Use ConcurrentHashMap for tracking connections

---

CHANGELOG.md
src/puppetlabs/pcp/broker/core.clj
test/puppetlabs/pcp/broker/core_test.clj

Many Jetty threads can result in modifying the connections or uri map.
When many updates occur concurrently, we can see lots of failed atom
updates resulting in much slower processing.
Switch to using a ConcurrentHashMap. It appears to scale better, and is
at least as fast for smaller numbers of clients.

(PCP-470) backport PCP-448: Use ConcurrentHashMap for tracking connections

---

README.md
dev-resources/Makefile.i18n
dev/user.clj
locales/messages.pot
project.clj
src/puppetlabs/pcp/broker/activemq.clj
src/puppetlabs/pcp/broker/capsule.clj
src/puppetlabs/pcp/broker/connection.clj
src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/activemq_test.clj
test/unit/puppetlabs/pcp/broker/connection_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/unit/puppetlabs/pcp/broker/in_memory_inventory_test.clj

In this PR we disable schema validations by default. We achieve that by removing the `^:always-validate` attribute from function definitions in this project.
To compensate for that a new lein alias - `tkv` - is added which is identical to the `tk` alias except it enables the schema validations before it runs trapperkeeper. Additionally the tests are updated to enable the validations by using the `schema.test/validate-schemas` fixture.

(PCP-467) Disable schema validations by default

---

locales/messages.pot
project.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/in_memory_inventory.clj

Gathering inventory responses for multiple query patterns is slow; for
1000 patterns, the response took ~5 seconds. In that particular case,
find-clients was evaluated lazily, and didn't happen until after
creating the response message and setting its expiry time. This resulted
in the message expiring before it was even sent when find-clients took
several seconds.
Force evaluation of find-clients before constructing the response
message, and speed up find-clients for multiple patterns.

(PCP-485) Improve inventory response performance

---

test/utils/puppetlabs/pcp/testutils/client.clj

The tests were prone to hitting the expiry limit, especially on slower HW. By increasing the limit we are increasing the chances the tests succeed on such HW.

(PCP-487) Increase PCP message expiry in tests

---

doc/authorization.md
resources/ext/config/conf.d/authorization.conf
src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

Adds a `/pcp-broker/connect` authorization check via tk-auth for
association requests.
Also changes tests to use shorter timeouts when expecting no response.

(PCP-384) Add `/pcp-broker/connect` authz check for association

---

doc/configuration.md
locales/messages.pot
src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj

The vNext route was supposed to be optional, but in practice was not.
Make it truly optional.

(PCP-506) Make vNext route truly optional

---

src/puppetlabs/pcp/broker/capsule.clj
test/unit/puppetlabs/pcp/broker/capsule_test.clj

As the Message schema does not guarantee that :sender is a PCP URI, we
cannot assume that in capsule/summarize, so we define CapsuleLog shcema
with :sender being a string.
Adding a few unit tests for the capsule namespace.

(PCP-516) CapsuleLog's sender may not be a PCP URI

---

locales/messages.pot
src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/utils/puppetlabs/pcp/testutils/client.clj

This commit increases expiry timeouts on PCP messages exchanged during tests by a factor of 60. This is to avoid occasional failures in CI we keep seeing.
In contrast to previous attempts to do the same this commit doesn't change the actual timeouts but rather redefines the function which applies the timeout values to the PCP messages: `puppetlabs.pcp.message/set-expiry`.
This has the desired effect of raising the timeouts for both the test code and the tested code at the same time (previous attempts were only raising the timeouts in the test code).
Additionally, timeout is also raised in the `puppetlabs.pcp.testutils.client/recv!` function which, too, was causing test failures by not waiting long enough for messages to be received.
Finally the …

(PCP-487) Increase timeouts in tests seriously

---

src/puppetlabs/pcp/broker/core.clj

With this commit the broker adds the id of the message that triggered
and error when replying with an error_message.

(PCP-524) Add error_message data's id when available

---

project.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/activemq_test.clj
test/unit/puppetlabs/pcp/broker/capsule_test.clj
test/unit/puppetlabs/pcp/broker/connection_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/unit/puppetlabs/pcp/broker/in_memory_inventory_test.clj

Adding new profiles that extend, respectively, the dev and test
profiles by using an :injection entry to enable schema validation
via (schema.core/set-fn-validation! true).
Refactoring dependencies of test profiles into new `test-base` profile.
Adding new `test-all` task that executes all tests with and without
schema verification.
==
Don't enable schema validation in test sources.
==
After disabling schema validation, capsule/wrap does not enforce that
the Message argument is a valid Message, so we can't test that anymore.
Note that with PCP-525 we will ensure that only valid PCP messages are
accepted by pcp-broker; we can safely drop the Message validation when
creating a Capsule.
==
Schema validation has been disabled by default; don't rely on it when
testing core/determine-next-state …

(PCP-526) Don't do schema validation in tests by default

---

src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/capsule_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/utils/puppetlabs/pcp/testutils/client.clj

Checking the validity of incoming messages only once, meaning:
- ignore messages other than associate_request before Association is
complete;
- authentication;
- authorization;
- TTL check.
Removing the transitions map that keept track of the state of the
association during the message double dispatch mechanism in favour of
making explicit the processing workflow.
Avoiding to update the 'connections' map at each processed message. In
practice, the onMessage handler will now update the map only if the
Connection instance being processed is actually updated; that happens
only in case of a successful associate_request.
Ensure incoming messages are valid Message instances by explicitly
validating against the Message schema; this is necessary as we don't
have schema validation enabled on …

(PCP-489) Improve onMessage handling

---

src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

Restore attempting to deliver expired messages (but continue to drop
them if delivery fails and they've expired). This makes the broker
somewhat resilient to clock skew.

(PCP-538) Restore initial delivery of expired messages

---

project.clj

Adds a profile :internal-mirrors that will include Puppet's internal mirror for downloading dependencies.
This can be used when pcp-broker is just being used as a component in testing (e.g. pxp-agent's acceptance tests).

(PCP-354) Add profile to use Puppet internal mirrors for deps

---

project.clj
src/puppetlabs/pcp/broker/core.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

- bumping to clj-pcp-common 0.5.2
- fixing process-message! test
- removing s/validate call for decoded messages in process-message!
- adding more unit tests for process-messasge!

(PCP-525) Rely on pcp-common.message for validating Messages

---

.gitignore

Add the access log location configured for dev/test to .gitignore.

(maint) Add access log to gitignore

---

.travis.yml
locales/messages.pot
project.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

This PR updates the project to use clj-parent for dependency versioning and changes the way how the broker name is determined. Here are the relevant commit descriptions:
Make use of the `parent-project` and `managed-dependencies` support in Leiningen 2.7.1 and rely on the `puppetlabs/clj-parent` project to define the versions of the majority of the project's dependencies.
Previously the broker name was read from the certificate specified in the ssl configuration of the webserver hosting the broker. This is not possible any more as:
- ssl may not be configured for the webserver at all
- the ssl configuration actually used by the webserver may differ from that specified in its configuration (it can be overridden)
So newly we try to obtain the broker name from the ssl-context actually used …

(PCP-597) Enable puppetserver collocating

---

dev/user.clj
project.clj

Previously a dedicated function was used for enabling of the schema checks.
Since we now have a profile for the same purpose, let's use it instead and drop the function.

(maint) Use profile for enabling schema checks

---

project.clj
test-resources/bootstrap.cfg
test/integration/puppetlabs/pcp/broker/service_test.clj

This pins a version of tk-metrics so that orchestrator and pcp-broker
will be compatible without requiring an override.

(maint) Update to clj-parent 0.2.4

---

CHANGELOG.md
project.clj

Incorporates PCP-620 fix into pcp-broker.

(maint) Bump pcp-common to 0.5.5 and prepare 0.8.5 release

---

CHANGELOG.md
locales/messages.pot
project.clj
src/puppetlabs/pcp/broker/core.clj

Catch and add debug logging when messages can't be delivered because the
connection is no longer available. It's normal operation for a client to
disconnect and leave an undeliverable response.
Observed some suspicious behavior in clj-pxp-puppet tests that might
have been related to the cond-let implementation. It doesn't improve the
code much, so remove it in place of nested ifs.

(maint) Log normal failure mode, remove cond-let

---

project.clj

Picks up a fix to trapperkeeper-status, and clj-parent now uses
trapperkeeper-webserver-jetty9 1.6.0.

(maint) Bump clj-parent to 0.3.2

---

test-resources/logback-test.xml
test/integration/puppetlabs/pcp/broker/service_test.clj

The test client can't determine when the broker registers a connection
without session association. Force it on tests that depend on multiple
clients being connected at once.

(maint) Fix test client

---

locales/messages.pot
project.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/inventory.clj
src/puppetlabs/pcp/broker/shared.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/unit/puppetlabs/pcp/broker/message_test.clj
test/unit/puppetlabs/pcp/broker/shared_test.clj

This PR introduces support for inventory updates. To be able to support the updates the `:inventory` map has been replaced with a more complex `:database` map which includes:
- `:inventory`, the original inventory mapping of a client Uri to a websocket connection
- `:updates`, a vector of updates (a vector of inventory change records)
- `:first-update-index`, the index of the first update in the `:updates` vector, this is an ever increasing (and overflowing index) which is increased when entries are removed from the beginning of the `:updates` vector
- `:subscriptions`, mapping of an Uri of a client which subscribed to inventory updates to a subscription record
Each subscription record consists of:
- `:connection`, the websocket connection on which the subscription was received, this is …

(PCP-600) Inventory updates

---

src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/inventory.clj
src/puppetlabs/pcp/broker/service.clj
src/puppetlabs/pcp/broker/shared.clj
test/integration/puppetlabs/pcp/broker/controllers_test.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/integration/puppetlabs/pcp/broker/subscription_test.clj
test/utils/puppetlabs/pcp/testutils/client.clj
test/utils/puppetlabs/pcp/testutils/server.clj
test/utils/puppetlabs/pcp/testutils/service.clj

Extract common service setup into a new testutils namespace, and split
subscription tests into their own namespace.
Also removes unused library inclusion and fixes a race in finishing
`it-closes-connections-when-not-running-test`.
Adds a stress test for many connections being established as
subscriptions are initiated. Ensures inventory stays insync.
Normally a client requesting updates is registered as a subscriber, and
an inventory response sent. It happens in this order to ensure no
updates are missed; the reverse order would allow for an inventory
response to be sent then a change in inventory to happen before the
subscription is registered.
However, the current order allows for an inventory update to be sent by
the subscription thread between registering as a subscriber and sending …

(PCP-707, PCP-600) Add stress test for subscriptions, fix race that sends inventory update before response

---

project.clj
src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/controllers_test.clj

Ensures controllers unsubscribe from inventory updates when they become
disconnected.
Depends on https://github.com/puppetlabs/pcp-broker/pull/168 and https://github.com/puppetlabs/clj-pcp-client/pull/71 (released in a pcp-client 1.1.0).

(PCP-712) Fix unsubscribe for controllers

---

test/integration/puppetlabs/pcp/broker/service_test.clj

Sometimes the test related to confirming that connections rejected due
to authorization rules receives a 1006 error code. This may be happening
because we close the connection during the on-connect callback.
I don't see a straight-forward way to reject the connection otherwise,
and failure to connect isn't something we should return detailed
information about, so accept this failure mode.

(maint) Accept 1006 for connection failure due to authz rules

---

doc/configuration.md
locales/eo.po
locales/messages.pot
project.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/inventory.clj
src/puppetlabs/pcp/broker/service.clj
src/puppetlabs/pcp/broker/shared.clj
test/integration/puppetlabs/pcp/broker/controllers_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/utils/puppetlabs/pcp/testutils/server.clj

When all configured controllers become disconnected from the broker,
schedule a task after a grace period (set to 45 seconds) that will
disconnect all clients. If a broker reconnects in that time, do not run
the task. Refuse client connections when all brokers are disconnected.

(PCP-701) purge clients after controller disconnections

---

test-resources/conf.d/pcp-broker.conf

A default controller config will cause pcp-broker to refuse connections.
This will cause pxp-agent acceptance tests that run against pcp-broker
to fail.

(maint) No controller config by default

---

src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/shared.clj
test/integration/puppetlabs/pcp/broker/controllers_test.clj

In a previous commit, status was changed to report error if all
controllers were disconnected. However, this is also normal behavior
when starting or stopping the service, which made status less
illuminating. Restore reporting starting and stopping status, and only
report error if the broker is running and all controllers are
disconnected.

(PCP-701) Fix state to report starting and stopping

---

doc/configuration.md
locales/eo.po
locales/messages.pot
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
src/puppetlabs/pcp/broker/shared.clj
test/integration/puppetlabs/pcp/broker/controllers_test.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/shared_test.clj
test/utils/puppetlabs/pcp/testutils.clj
test/utils/puppetlabs/pcp/testutils/client.clj

Add a config setting to limit the number of client connections allowed
to the broker. Defaults to 0 (unlimited).

(ORCH-1601) add connection limit

---

project.clj
resources/ext/config/conf.d/metrics.conf
test/utils/puppetlabs/pcp/testutils/service.clj

Bump to clj-parent 0.6.1 which includes trapperkeeper-metrics 1.0.0.
No code changes are required for this update.
The `:enabled` setting in the test metrics config was removed as this setting
had been deprecated and acted as a no-op for a long time; tk-metric 1.0.0
removed it entirely.
The metrics.conf included in packaging was updated to match the new config for
tk-metrics 1.0. As with the previous metrics.conf, it enables the JMX metrics
reporter. It also includes commented out example config for configuring the
Graphite reporter. The updates to this config file are not expected to cause
any problems because 1) it was never configurable using the PE module, and 2)
there is no documentation for how to configure any settings in it.

(PE-19981) Bump to clj-parent 0.6.1

---

CHANGELOG.md
doc/configuration.md
project.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
test/integration/puppetlabs/pcp/broker/controllers_test.clj

45000 seems a bit too aggressive, since JVM restarts could plausibly
take that long. This bumps the timeout to 90000.

(maint) raise default controller disconnection graceperiod

---

.travis.yml
ext/travisci/secscan.sh

Enabling code scans for some basic security checks. Currently the script only looks for read-string instances. 
Supersedes PR #191.

(SEC-36) Enabling static Clojure code scans using a shell script

---

.travis.yml
CHANGELOG.md
project.clj
src/puppetlabs/pcp/broker/core.clj
test/utils/puppetlabs/pcp/testutils/server.clj

blocked on https://github.com/puppetlabs/clj-pcp-client/pull/77
This changed the method of instrospecting brokername from the ssl
context to use only public methods.

(PCP-741) Upgrade jetty to 9.4

---

CHANGELOG.md
project.clj

Remove unused dependencies, and pickup metrics-clojure from clj-parent.
Bump to clj-parent 1.1.0 for the addition of metrics-clojure. We also
use ssl-utils in the core implementation, so move it out of test-only
dependencies into standard dependencies.

(maint) Cleanup dependencies

---

src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/util.clj

This PR makes sure errors or messages received on stale websocket connections are handled gracefully. A stale connection in this context means a connection which is not present in the broker's inventory any longer.
Previously it was not the case which could lead to validation errors when there was an attempt to log the connection details for connection which was not found in the broker's inventory.

(PCP-737) Handle events on stale connection gracefully

---

.travis.yml
test/integration/puppetlabs/pcp/broker/controllers_test.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/utils/puppetlabs/pcp/testutils.clj

Introduce a small wait after receiving the on-close message to ensure
the websocket object registers that the connection is closed.

(PCP-735) Allow disconnect to resolve

---

CHANGELOG.md
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/shared.clj

When a PCP connection from pcp-broker to the controller (orchestrator) is
established, there is a brief window of time during which the connection is
able to receive messages but is not yet considered
"connected" by our internal record-keeping.
The first thing orchestrator does when a broker connects is immediately
send an inventory request.  The inconsistency in state in the broker means
that it's possible it will receive that request before it thinks it's
connected, and currently it will reject the message. That causes
orchestrator to never receive an inventory response (or subsequent
inventory updates) from the broker, rendering any agents connected to that
broker inaccessible until one service or the other is restarted.
This inconsistency happens because we have multiple layers of …

(PCP-760) Wait for connection before processing controller messages

---

src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
src/puppetlabs/pcp/broker/shared.clj
test/unit/puppetlabs/pcp/broker/shared_test.clj

Adds a `pcp-broker.max-message-size` configuration option that
configures the max binary message size for WebSocket sessions. This
would allow large messages to be sent by clients.

(PCP-491) Make max message size configurable

---

project.clj
test/unit/puppetlabs/pcp/broker/core_test.clj

Primarily brings in new trapperkeeper-webserver-jetty9 version.

(maint) Bump clj-parent to 1.4.2

---

src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/shared.clj
test/integration/puppetlabs/pcp/broker/controllers_test.clj
test/unit/puppetlabs/pcp/broker/shared_test.clj
test/utils/puppetlabs/pcp/testutils/client.clj

Accepting websocket upgrades before rejecting the connection causes
clients to get a successful connection before it immediately disappears.
It's difficult to distinguish that this is a configuration issue - vs a
broker going away - to determine whether the client should immediately
attempt to reconnect and get a new broker from the load balancer, or
delay reconnects.
Update the broker to reject connections immediately - by disabling the
routing handler - rather than accepting a websocket upgrade before
disconnecting.

(PCP-777) Reject connections before websocket upgrade

---

src/puppetlabs/pcp/broker/core.clj

Previously, this setting was only being used to control the max message
size for connections from pxp-agents. That caused orchestrator messages
to use the default 64k limit, which is too small for task requests
involving large metadata. We now thread that setting through to the
outbound connections pcp-broker makes.

(PCP-854) Honor max-message-size for orchestrator connections

---

ezbake/config/docker/bootstrap.cfg
ezbake/config/docker/conf.d/auth.conf
ezbake/config/docker/conf.d/global.conf
ezbake/config/docker/conf.d/metrics.conf
ezbake/config/docker/conf.d/pcp-broker.conf
ezbake/config/docker/conf.d/web-routes.conf
ezbake/config/docker/conf.d/webserver.conf
ezbake/config/docker/logback.xml
ezbake/config/docker/request-logging.xml
project.clj

This adds config to project.clj and the ezbake/config/docker directory
in order to build a docker image via `lein ezbake docker-build`. This
image contains only pcp-broker and accepts its config via environment
variables.

(ORCH-2261) Configure to build docker image via ezbake

---

project.clj
src/puppetlabs/pcp/broker/core.clj

This changes closing the pcp connection behavior to use disconnect in place of close, in hopes that disconnect will stop the connection more quickly and reduce the number of file descriptors opened by pcp at any given time.

(PCP-862) Use disconnect rather than close

---

CHANGELOG.md
src/puppetlabs/pcp/broker/core.clj
test/integration/puppetlabs/pcp/broker/service_test.clj

This removes the `close!` call before disconnecting a superseded connection. It was originally left to preserve the code and reason in logging, but appeared to leave unused sockets open, consuming resources even when disconnect was called. Using just `disconnect` frees the resources, and we determined there was already sufficient logging of pxp-agents being superseded to lose the 'Superseded' message.

(PCP-862) Remove `close!` call before disconnecting

---

test-resources/conf.d/authorization.conf

4ed40af updated clj-parent to a version that includes
trapperkeeper-status 1.1.0, which now uses trapperkeeper-auth to guard
the status routes. That caused status requests to fail against
pcp-broker when running with the config in test-resources (as the
pxp-agent acceptance tests use).
We now include a rule in the authorization.conf that explicitly allows
unauthenticated access to the status endpoint.

(PCP-866) Allow status requests in test authorization config

---

doc/configuration.md

Adding a configuration reference to max-message-size so it accurately reflects the code base.

(maint) Add reference to max-message-size parameter

---

project.clj

This adds the bouncycastle dependency to the `:integration` profile just as it is part of the `:dev` profile. It also creates a new `:internal-integration` which allows the `:integration` profile to be used alongisde the mirrors specified in `:internal-mirrors`.

(maint) Add bouncycastle to integration profile

---

.travis.yml
project.clj

Handles a condition where an HTTP exception occurring during a WebSocket
Upgrade should be retried. This commonly happens when pe-orchestration-services
is restarted.

(ORCH-2283) retry HTTP errors during WebSocket upgrade

---

src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
src/puppetlabs/pcp/broker/shared.clj
test/unit/puppetlabs/pcp/broker/shared_test.clj

pcp-broker appears to have hang on to SSLContexts and connections longer than necessary in dynamic environments where agents frequently come and go. While idle-timeout is most likely not contributing significantly to that, it seems like a simple thing to lower and help in a small way.

(maint) Allow adjusting the idle timeout and lower its default

---

project.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
test-resources/bootstrap.cfg
test/integration/puppetlabs/pcp/broker/service_test.clj
test/utils/puppetlabs/pcp/testutils/service.clj

tk-jetty9 will reload the SSLContextFactory for pcp-broker when changes
to the CRL occur. In doing so new connections will use the CRL updates.
However pcp-broker, by design, keeps connections open for long durations.
This can result in many different SSLContexts in the heap with different
versions of the CRL. Coupled with large CRLs this can take up a
significant portion of the heap (10-20%).
This brings in tk-filesystem-watcher as a dependency and, like
tk-jetty9, watches the CRL for updates. When it has changed the client
are disconnected fromt the server. This is under the assumption that the
clients will reconnect and the server will be able to use the new CRL.
Some caveats:
- The SSLContextFactory is not guaranteed to have reloaded by the time
the first agent reconnects. This might …

(PCP-900) Close connections after CRL update

---

doc/configuration.md
src/puppetlabs/pcp/broker/connection.clj
src/puppetlabs/pcp/broker/core.clj
src/puppetlabs/pcp/broker/service.clj
src/puppetlabs/pcp/broker/shared.clj
test/integration/puppetlabs/pcp/broker/service_test.clj
test/unit/puppetlabs/pcp/broker/connection_test.clj
test/unit/puppetlabs/pcp/broker/core_test.clj
test/unit/puppetlabs/pcp/broker/shared_test.clj

Previously, in 44ce091, we began closing all connections after a CRL
update to prevent stale SSLContexts from being held in memory. However,
the previous change dropped all connections in quick succession and
there was some concern that it could cause undo spikes in load from a
thundering herd of reconnection attempts.
This patch creates a background thread (the same as how we send inventory
updates) that every X milliseconds tries to close any Connections in the
inventory marked expired. It also throttles the attempt to close all
connections by sleeping Y milliseconds between each Connection it
closes. X and Y are configurable by the new config values
`crl-check-period` and `expired-conn-throttle` respectively. The default
to 60 seconds between CRL checks and 30 milliseconds between …

(PCP-900) Throttle connection resets after crl is expired

---

src/puppetlabs/pcp/broker/core.clj

The structured logging macro `maplog` will attempt to serialize a
URI, however we need its string representation for our logging. Coerce,
URIs to strings when closing connections due to CRL updates.

(maint) Coerce URI to str before passing to sl/maplog

---

doc/configuration.md
src/puppetlabs/pcp/broker/service.clj

When the controller-whitelist setting was moved to controller-allowlist it brought up a discussion around what reasonable defaults to expect for the setting. This commit updates the defaults to include the rpc messages where previously they were not included.

(PE-30041) Add rpc_*_requests to default allowed message types

---

project.clj

This commit adds a Bouncycastle dependency to the uberjar profile that
was missed when Bouncycastle usage was re-factored to support a
FIPS/non-FIPS split. The dependency allows `lein uberjar` to complete
instead of failing during AOT compilation.

(maint) Fix lein uberjar

---

project.clj

To resolve a number of Jetty CVEs

(PE-31800) update clj-parent to 4.6.19

---

project.clj

This commit removes all references to the pl-clojure-style repo. This was used
for linting / style checking in the past, but hasn't been used for quite some
time, so no reason to keep the `cljfmt` profile for running it.

(maint) Remove pl-clojure-style linter

---

project.clj

This brings in a new version of http-client that conditionally
allows auth headers when being redirected.

(maint) update clj-parent to 4.8.3

---

CHANGELOG.md
project.clj

This updates clj-parent to 5.2.9, which is now managing `stylefruits/gniazdo`. The dependency is part of pcp-client, which, as of 1.4.0,  is using the version determined by clj-parent.
This also prepares for a new release.

(PE-34654) update clj-parent, pcp-client

---

project.clj

This adds a ci profile, and removes the duplicate dependency for pcp-common which comes from the pcp-client.

(maint) add ci-profile, remove duplicate dependency

---

CHANGELOG.md
project.clj
src/puppetlabs/pcp/broker/core.clj

This adds some exception handling to the connection setup to allow exceptions to be logged.  Prior to this change, an exception would stop the broker from correctly starting.
This also adds some additional logging to help diagnose issues.

(maint) handle connection exceptions

---

project.clj

This commit updates clj-parent to 7.3.6 and removes the pins for tk-jetty10 and tk-metrics.

(maint) update clj-parent (7.3.7), remove pins
