puppetlabs/pcp-broker

CHANGELOG.md, doc/configuration.md, project.clj
We change the authorization subsystem completely, so bump .Y
=> (maint) prepare for 0.4.0 release

src/puppetlabs/pcp/broker/connection.clj, src/puppetlabs/pcp/broker/core.clj
In the case where a connection did not provide an acceptable peer certificate,
common-name will be nil.  There were places where we expected common-name would
always be a string, so update the schemas.
As part of this we refactor connection/make-connection a little to
extract the common name as part of wrapping the websocket, so we
can drop the use of get-cn at log time, this is a slight performance
win.
=> (maint) Allow for common-name of a connection to be nil

src/puppetlabs/pcp/broker/core.clj
During the review of #104 these style enhancements were identified but not considered essential to the change at hand.  Here we clean those up.
=> Style changes observed in the review of #104

src/puppetlabs/pcp/broker/core.clj, test/integration/puppetlabs/pcp/broker/service_test.clj
If broker recieves a message or new connection while it is not in
the state :running, close the connection with code 1011:
https://tools.ietf.org/html/rfc6455#section-7.4
1011 indicates that a server is terminating the connection because
it encountered an unexpected condition that prevented it from
fulfilling the request.
=> PCP-294 Reject connections before we start

README.md
=> (maint) Add Maintenance section to README

.gitignore
=> (maint) Add eng-resources directory to .gitignore

src/puppetlabs/pcp/broker/core.clj
Without this change, serializing a list of clients to json can cause the
message to expire before it's sent if that serialization takes a
significant amount of time. Ensure setting the expiration time is the
last thing we do before attempting to send the message.
=> (PCP-496) Set inventory_response message expiration last

CHANGELOG.md
=> (packaging) Prepare for 0.7.1 release

project.clj
=> (PCP-528) Fix unit and integration lein profiles

doc/authentication.md, doc/logging.md, locales/messages.pot, resources/messages_log_parser.py, src/puppetlabs/pcp/broker/capsule.clj, src/puppetlabs/pcp/broker/connection.clj, src/puppetlabs/pcp/broker/core.clj, test-resources/log/request-logging.xml, test-resources/logback-dev.xml, test-resources/logback-test.xml
Logging incoming PCP messages with the pcp-access logger whenever the
onMessage handler is invoked.
=> (PCP-385) Add pcp-access logger and improve docs

doc/README.md, doc/resources.md
See the ticket for detailed measurements that led to these
recommendations.
=> (PCP-672) Document broker resource usage

src/puppetlabs/pcp/broker/inventory.clj, test/integration/puppetlabs/pcp/broker/controllers_test.clj, test/integration/puppetlabs/pcp/broker/subscription_test.clj, test/utils/puppetlabs/pcp/testutils/server.clj, test/utils/puppetlabs/pcp/testutils/service.clj
Some new tests and and a minor improvement around subscriptions.
Also identified a problem with controllers remaining subscribed after they disconnect. Created [PCP-712](https://tickets.puppetlabs.com/browse/PCP-712).
=> (maint) Subscription improvements

locales/eo.po, locales/messages.pot, src/puppetlabs/pcp/broker/core.clj, test/integration/puppetlabs/pcp/broker/controllers_test.clj
Add a bit more logging around controller disconnection/reconnection.
=> (maint) logging improvements

project.clj, resources/ext/config/conf.d/metrics.conf, test/utils/puppetlabs/pcp/testutils/service.clj
Reverts puppetlabs/pcp-broker#184
=> Revert "(PE-19981) Bump to clj-parent 0.6.1"

locales/pcp-broker.pot, project.clj, src/puppetlabs/pcp/broker/core.clj, src/puppetlabs/pcp/broker/service.clj, src/puppetlabs/pcp/broker/shared.clj
Structured logging 0.2.0 introduced a breaking change. The last argument
of maplog is now expected to be a function that accepts the structured
log data as an argument. Formatting is no longer handled by maplog.
Update use of maplog to use functions and handle formatting.
=> (maint) Update to structured logging 0.2.0

src/puppetlabs/pcp/broker/core.clj, src/puppetlabs/pcp/broker/service.clj, src/puppetlabs/pcp/broker/shared.clj
This PR updates the log levels of the logged messages according to the following definition:
ERROR: abnormal failure to startup, establish a connection, or deliver a message
WARNING: authorization or authentication failure, or failure to process a message
INFO: change in service or connections (connect/disconnect)
DEBUG: sending or responding to messages with identifying information (but not content), completing state transitions (namely those logged at INFO)
TRACE: receiving messages with full contents, full contents of responses
=> (PCP-732) Refine logging in broker

src/puppetlabs/pcp/broker/core.clj, src/puppetlabs/pcp/broker/service.clj, src/puppetlabs/pcp/broker/shared.clj, test/integration/puppetlabs/pcp/broker/controllers_test.clj, test/integration/puppetlabs/pcp/broker/service_test.clj, test/unit/puppetlabs/pcp/broker/core_test.clj, test/unit/puppetlabs/pcp/broker/shared_test.clj
Cleanup of messages based on comments given in review of PCP-732 (PR #196).
=> (maint) Message cleanup

src/puppetlabs/pcp/broker/core.clj
A recent PR made sure events on stale connection are handled gracefully. (A stale connection meaning a connection which is not present in the broker's inventory any longer.) But it failed to address similar problem on controller connections which are kept in a separate inventory / registry.
So this PR makes sure even events on stale controller connections are handled gracefully.
Not that it is easier to review using [?w=1](199/files?w=1)
=> (PCP-737) Handle events on stale controller connections too

CHANGELOG.md, project.clj
Also update clj-parent to 1.2.1.
=> (packaging) Prepare for 1.4.0 release

.travis.yml, ext/travisci/test.sh, project.clj
We are making the change from nexus to artifactory
=> (maint) Use artifactory instead of nexus

.travis.yml, CHANGELOG.md, project.clj, test/integration/puppetlabs/pcp/broker/controllers_test.clj, test/integration/puppetlabs/pcp/broker/service_test.clj, test/utils/puppetlabs/pcp/testutils/client.clj, test/utils/puppetlabs/pcp/testutils/service.clj
Updates dependencies and some code that was affected by changed behavior to support Java 9.
=> (maint) Add support for Java 9

doc/authorization.md, doc/configuration.md, ezbake/config/docker/conf.d/pcp-broker.conf, src/puppetlabs/pcp/broker/core.clj, src/puppetlabs/pcp/broker/service.clj, test-resources/conf.d/pcp-broker.conf, test/integration/puppetlabs/pcp/broker/controllers_test.clj
This commit changes instances of `whitelist` to `allowlist`.
=> (PE-30041) Remove harmful term from pcp-broker config
